#import anything you need here
import main_character as mc
import the_shopkeeper as sc2
import item


def start(player):
    #walking up to the shopkeeper
    print("After decding on picking up the potion, you walk up to the counter")
    input()
    print("You look at the shopkeeper and told that you will be getting this potion")
    input()
    print("Shopkeeper : But that's not what you came here, is it?")
    input()
    print(player.name,": Well. I didn't thought about coming here...")
    input()
    print("Shopkeeper : Oh, but you are!")
    input()
    print("Shopkeeper : And you are looking for this.")
    input()
    print("The shopkeeper took something out from under the conuter")
    input()
    print("It's a map")
    input()
    print("Shopkeeper : This is what you came for.")
    input()
    print("Shopkeeper : Is this all?")
    print("Map - 15 coins\nPotion - 10 coins")
    input()
    which_way = input("What would you like to do?\n\"S\" - Steal the items\n\"D\" - Don't buy the items\n\"P\" - Purchase the items")
    input()
    
    #steal the items
    if which_way == 'S':
        print("You look at the items on the counter and thought about just stealing them")
        input()
        print("The shopkeeper was already looking at you")
        input()
        print("and he knew what you were thinking")
        input()
        print("Shopkeeper : Don't even think about it.")
        input()
        print("You look up at him surprised")
        input()
        print(player.name,": I wasn't thinking about anything.")
        input()
        print("Shopkeeper : Mhm, sure you weren't.")
        input()
        print("Shopkeeper : So, are you buying?")
        input()
        print(player.name,": Yeah.")
        input()
        print("Shopkeeper : 10 bronze coins, 15 silver coins")
        input()
        print(player.name,": Alright, here you go.")
        player.money -= 35
        sc2.the_shopkeeper.money += 35
        print("You give 35 coins to the Shopkeeper and took the items")
        input()
        sc2.the_shopkeeper.inventory.remove('map')
        player.inventory.append("map")
        player.inventory.append("potion")
        print("You have received a ['map']")
        print("You have received a ['potion']")
        print("Inventory:",player.inventory)
        input()
        print("You turn around and head for the door")
        input()
        print("When you got of the the door, you decide to the use the map")
        input()
        Map = item.Item("Map")
        print(Map.name)
        print("x:",Map.x)
        print("y:",Map.y)
        print(player.name,": What is it that this map is talking me?")
        input()

    #Choose to not buy the items
    elif which_way == 'D':
        print(player.name,": Yeah, nevermind. I don't think I want these items anymore.")
        input()
        print("Shopkeeper : Hey, if you don't want the potion anymore. At least, get the map.")
        input()
        print("Shopkeeper : Isn't it the whole point that you are here?")
        input()
        print(player.name,": hmm, okay sure.")
        input()
        print("Shopkeeper : 15 coins")
        input()
        print(player.name,": Alright, here you go.")
        input()
        player.money -= 15
        sc2.the_shopkeeper.money += 15
        print("You give 15 coins to the Shopkeeper and took the map")
        input()
        sc2.the_shopkeeper.inventory.remove('map')
        player.inventory.append("map")
        print("You have received a ['map']")
        print("Inventory:",player.inventory)
        input()
        print("You turn around and head for the door")
        input()
        print("When you got of the the door, you decide to the use the map")
        input()
        Map = item.Item("Map")
        print(Map.name)
        print("x =",Map.x)
        print("y =",Map.y)
        input()
        print(player.name,": What is it that this map is taking me?")
        input()
        
    #purchase the items
    else:
        print(player.name,": I would like to purchase these items")
        input()
        print("Shopkeeper : 10 bronze coins, 15 silver coins")
        input()
        print(player.name,": Alright, here you go.")
        player.money -= 35
        sc2.the_shopkeeper.money += 35
        print("You give 35 coins to the Shopkeeper and took the items")
        input()
        sc2.the_shopkeeper.inventory.remove('map')
        player.inventory.append("map")
        player.inventory.append("potion")
        print("You have received a ['map']")
        print("You have received a ['potion']")
        print("Inventory:",player.inventory)
        input()
        print("You turn around and head for the door")
        input()
        print("When you got of the the door, you decide to the use the map")
        input()
        Map = item.Item("Map")
        print(Map.name)
        print("x =",Map.x)
        print("y =",Map.y)
        print(player.name,": What is it that this map is taking me?")
        input()
