def start(player):
    #walks into the shop
    print("You walks into the shop")
    input()
    print("You see there are many things that hanging from the ceiling and on the shelves")
    input()
    print("Then you notice the man, which you are guessing is the shopkeeper, standing at the counter")
    input()
    which_way = input("What would you like to do?\n\"M\" - Walk up to the man\n\"L\" - Look around the shop\n\"W\" - Walk out")
    input()
    
    #look around
    if which_way == "L":
        print("You decide to look around the shop")
        input()
        print(player.name,": I think I should look around first")
        input()
        print("You walk around the hanging objects as you weren't sure what they are")
        input()
        print("So you deicde to check out the shelves")
        input()
        print("As you are looking through each one, one of them has a potion with strange color liquid")
        input()
        print("You pick up the poyion, thinking it to be some weird potion, but actually...")
        input()
        print("On the tag, it reads 'Potion of Health (restore 50 health)' - 10 coins")
        input()
        print(player.name,": Sounds interesting.")
        input()
        print("You decide on picking up this potion")
        input()

    #walk out
    elif which_way == "W":
        print("You decide to walk out")
        input()
        print(player.name,": Yeah, I'm not sure about that...")
        input()
        print("You turn around and went straight for the door")
        input()
        print("You try turning the door knob but it wouldn't budge")
        input()
        print(player.name,": Well, this is unfortunate...")
        input()
        print("You turn back around and went straight to the counter")
        input()
        print("When you were walking, you notice a potion standing out the rest of the potions")
        input()
        print("You pick up the potion, thinking it to be some weird potion, but actually...")
        input()
        print("On the tag, it reads 'Potion of Health (restore 50 health)' - 10 coins")
        input()
        print(player.name,": Sounds interesting.")
        input()
        print("You decide on picking up this potion")
        input()

    #walk up to the man
    else:
        print("You decide to walk up to the counter")
        input()
        print(player.name,": Let's just this over with...")
        input()
        print("When you were walking, you notice a potion standing out the rest of the potions")
        input()
        print("You pick up the potion, thinking it to be some weird potion, but actually...")
        input()
        print("On the tag, it reads 'Potion of Health (restore 50 health)' - 10 coins")
        input()
        print(player.name,": Sounds interesting.")
        input()
        print("You decide on picking up this potion")
        input()
